### ISSUE TITLE
Are these tested by you? 

### ISSUE THREAD

**Issue by waheed0332** [MPieter/YOLOv4-CoreML-Converter#1]
What's iOS version did you test on?

**Comment by MPieter** [comment]
I ran on iOS 13, currently only around 3-4 FPS. Currently one mish layer is mapped on multiple CoreML layers which I think causes the performance decrease compared to YOLOv3.

**Comment by MPieter** [comment]
I am trying to implement a custom CoreML layer which does this in 1 step.
